---
- name: Get Gitlab repository installation script
  get_url:
    url: "https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh"
    dest: /tmp/script.deb.sh
    mode: 0744

- name: Install Gitlab repository
  shell: bash /tmp/script.deb.sh
  args:
    creates: "/etc/apt/sources.list.d/runner_gitlab-runner.list"
  become: yes

- name: Install GitLab Runner
  apt:
    name: "gitlab-runner"
    state: present
