---
dist: xenial
sudo: true

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y software-properties-common
  - sudo apt-add-repository --yes --update ppa:ansible/ansible
  - sudo apt-get install ansible  

script:
  - ansible-playbook playbook.yml -i inventory --syntax-check
