---
- name: Create MySQL databases
  mysql_db:
    login_user: "{{ root_password }}"
    login_password: "{{ root_password }}"
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8mb4_unicode_ci') }}"
    encoding: "{{ item.encoding | default('utf8mb4') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mysql_databases }}"
